# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: jkcclemens
ko_fi: jkcclemens
liberapay: jkcclemens
custom: https://paypal.me/jkcclemens
