language: rust
cache:
  cargo: true
  directories:
    - $HOME/libsodium
addons:
  apt:
    packages:
      - cmake
      - libpq-dev
before_script:
  - . .travis/libsodium.sh
script:
  - cargo build --verbose --all
rust:
  - nightly
matrix:
  fast_finish: true
notifications:
  email: false
