language: rust
cache:
  cargo: true
  directories:
    - $HOME/libsodium
addons:
  apt:
    packages:
      - cmake
      - libpq-dev
before_script:
  - .travis/cache_check.sh
  - . .travis/libsodium.sh
script:
  - cargo build --verbose --all
# Remove the local crate's build files, as they only add bloat to the cache.
# TODO: Remove unused dependency build files
before_cache:
  - rm -rfv target/debug/paste.d
  - rm -rfv target/debug/incremental/{paste,build_script_build}-*
  - rm -rfv target/debug/.fingerprint/paste-*
  - rm -rfv target/debug/build/paste-*
  - rm -rfv target/debug/deps/paste-*
  - cargo clean -p paste
rust:
  - nightly
matrix:
  fast_finish: true
notifications:
  email: false
