[general]
site_name = "paste"
site_domain = "paste.gg"
# Set this to include custom content on the /about page
# If not set, the About link in the navbar will not be displayed
# about_file = "about.html"

[admin]
# A random key used to become the first admin. Anyone who knows or guesses this can become an admin
# if there are no other admins registered. This can be unset once one admin is registered.
# key = ""

[pastes]
# Require users to sign in before they can created pastes?
sign_in_to_create = false

[registration]
# Should registration be open to everyone?
open = true
# If registration is not open, users will be allowed to sign up with these emails.
whitelisted_emails = [
  # "example@example.com",
]

[store]
# The path on the filesystem where pastes will be stored.
# For production docker, this should be set to "/store"
path = "./store"

# Sender information for emails sent from the server
[email.sender]
name = ""
from = ""

# SMTP information for emails sent from the server
# paste enforces TLS without negotiation
[email.smtp]
# address for smtp
address = ""
# domain for validating cert
domain = ""
port = 0
username = ""
password = ""
