[general]
site_name = "paste"
site_domain = "paste.gg"
# Set this to include custom content on the /about page
# If not set, the About link in the navbar will not be displayed
# about_file = "about.html"
# If this is enabled, avatars will be downloaded and converted into WebP files at 90% quality when
# requested.
# Converted avatars are cached in redis for 10 minutes.
convert_avatars = false

[admin]
# A random key used to become the first admin. Anyone who knows or guesses this can become an admin
# if there are no other admins registered. This can be unset once one admin is registered.
# key = ""
# Should normal admins be allowed to edit the config? Superadmins are always allowed.
admins_can_edit_config = false

[pastes]
# Require users to sign in before they can created pastes?
sign_in_to_create = false

[registration]
# Should registration be open to everyone?
open = true
# If registration is not open, users will be allowed to sign up with these emails.
whitelisted_emails = [
  # "example@example.com",
]

[store]
# The path on the filesystem where pastes will be stored.
# For production docker, this should be set to "/store"
path = "./store"

# Sender information for emails sent from the server
[email.sender]
name = ""
from = ""

# SMTP information for emails sent from the server
# paste enforces TLS without negotiation
[email.smtp]
# address for smtp
address = ""
# domain for validating cert
domain = ""
port = 0
username = ""
password = ""

[[filter]]
kind = "regex"
match = '''(?ix)
\b
(
  filter\ some\ stuff\ here |
  more\ filtered\ words
)'''
action = "fake_message"
message = "an error occurred"
on = ["title", "description", "content"]
by = ["anonymous"]
