[global]
template_dir = "web/templates"

# uncomment this to enable server TLS
# [global.tls]
# certs = "path/to/certs.pem"
# key = "path/to/key.pem"

[development]
secret_key = "gt/gjaCknItthlJK1Cn/WOhpccnW7sD6T3r8OAP4Mxg="
