[icons]
admin-delete = "shield-remove"
chevron-down = "chevron-down"
delete = "delete"
display-name = "account-card-details"
edit = "pencil"
email = "email"
expires = "timer"
eye = "eye"
eye-closed = "eye-off"
heart = "heart"
language = "code-tags"
lock = "lock"
open-lock = "lock-open"
password = "asterisk"
paste = "clipboard"
question = "help-circle"
shield = "shield"
username = "account"
visibility = "earth"
