version: '3'
services:
  backend:
    build: run
    command: /run.sh --release --verbose
    restart: unless-stopped
    volumes:
      - "../:/paste"
      - "./run/.cargo/registry:/root/.cargo/registry"
      - "./run/.cargo/git:/root/.cargo/git"
    depends_on:
      - postgres
      - redis
      - sidekiq
    environment:
      - ROCKET_ENV=prod
  redis:
    image: redis:alpine
    restart: unless-stopped
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=paste
      - POSTGRES_PASSWORD=paste
  sidekiq:
    build: sidekiq
    depends_on:
      - redis
    volumes:
      - "../:/paste"
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/sites:/etc/nginx/sites:ro"
      - "./nginx/certs:/etc/nginx/certs:ro"
      - "../webserver/web/static:/etc/nginx/web/static:ro"
